language: node_js
node_js:
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
sudo: false
branches:
    only:
    - master

# Run npm test always
# Run npm docs only when its the master branch build and node 8
script:
    - "npm test"
    - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "master" && "$node_js" = "8" ]]; then npm run docs; fi'
after_success:
    - 'if [ "$node_js" = "8" ]; then npm run coveralls; fi'
addons:
    code_climate:
        repo_token: 1945f7420d920a59f1ff8bf8d1a7b60ccd9e2838a692f73a5a74accd8df30146
